name: Release AddOn

on:
  push:
    tags:
      - '**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

jobs:
  release: # "release" is a job, you can name it anything you want
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # reads history for commit changelog

      - uses: BigWigsMods/packager@v2
